### ISSUE TITLE
error using grafana_datasource: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by gretel** [sous-chefs/grafana#106] opened 2015-11-13 17:44 UTC
```
* grafana_datasource[graphite.in] action create[2015-11-13T17:40:26+00:00] ERROR: Connection refused.
[2015-11-13T17:40:26+00:00] ERROR: Connection refused.


================================================================================
Error executing action `create` on resource 'grafana_datasource[graphite.in]'
================================================================================

NoMethodError
-------------
undefined method `each' for nil:NilClass

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:27:in `block in class_from_file'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/xpl_grafana/recipes/_grafana.rb

19: grafana_datasource 'graphite.in' do
20:   datasource(
21:     type: 'graphite',
22:     url: 'http://graphite1.in.whatever.com',
23:     access: 'proxy'
24:   )
25: end
26:


------------------
# Declared in /tmp/kitchen/cache/cookbooks/xpl_grafana/recipes/_grafana.rb:19:in `from_file'

grafana_datasource("graphite.in") do
 action [:create]
 retries 0
 retry_delay 2
 default_guard_interpreter :default
 declared_type :grafana_datasource

 recipe_name "_grafana"
 datasource {:type=>"graphite", :url=>"http://graphite1.in.whatever.com", :access=>"proxy", :name=>"graphite.in"}
 host "localhost"
 admin_user "admin"
 admin_password "password"
end
```

**Comment by lanyonm** [comment] 2015-11-13 17:49
Hey @gretel,
The important bit is at the top of what you pasted above:

```
* grafana_datasource[graphite.in] action create[2015-11-13T17:40:26+00:00] ERROR: Connection refused.
[2015-11-13T17:40:26+00:00] ERROR: Connection refused.
```

Can you see from the Grafana log why it's refusing the connection?

**Comment by gretel** [comment] 2015-11-13 17:50
@lanyonm, sure, but i have been testing this case explicitly - the error thrown does not relate to the actual cause, may i propose to handle this case inside your cookbook's logic?

**Comment by iksaif** [comment] 2015-11-20 10:17
Same issue here:

<pre>
       [2015-11-20T09:57:28+00:00] ERROR: Connection refused.
       [2015-11-20T09:57:28+00:00] ERROR: Connection refused.
       
           
           ================================================================================
           Error executing action `create` on resource 'grafana_datasource[graphite]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `each' for nil:NilClass
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:27:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/grafana-storage/recipes/default.rb
           
            27:   grafana_datasource name do
            28:     datasource(
            29:       conf.to_hash
            30:     )
            31:   end
            32: end
</pre>

<pre>
[root@grafana-centos-65 ~]# ps aux | grep grafana
grafana   2728  0.0  2.7 271344 13052 ?        Sl   09:57   0:00 /usr/sbin/grafana-server --pidfile=/var/run/grafana-server.pid --config=/etc/grafana/grafana.ini cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana
root      2858  0.0  0.1 103244   888 pts/0    S+   10:14   0:00 grep grafana
</pre>

<pre>
# tail /var/log/grafana/grafana.log 
2015/11/20 09:57:28 [I] Migrator: exec migration id: create dashboard_snapshot table v5 #2
2015/11/20 09:57:28 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v5
2015/11/20 09:57:28 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5
2015/11/20 09:57:28 [I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5
2015/11/20 09:57:28 [I] Migrator: exec migration id: alter dashboard_snapshot to mediumtext v2
2015/11/20 09:57:28 [I] Migrator: exec migration id: create quota table v1
2015/11/20 09:57:28 [I] Migrator: exec migration id: create index UQE_quota_org_id_user_id_target - v1
2015/11/20 09:57:28 [I] Created default admin user: admin
2015/11/20 09:57:28 [I] Creating json dashboard index for path: /var/lib/grafana/dashboards
2015/11/20 09:57:28 [I] Listen: http://localhost:3000
</pre>

I suspect that grafana takes some time to be really ready to listen, and the cookbooks runs before that. Exiting from the init script only when grafana is listening would solve that.

Not that there is an additional issue, on the second run:

<pre>
      [2015-11-20T10:24:32+00:00] ERROR: Invalid grafana_user and grafana_sess.
       
           
           ================================================================================
           Error executing action `create` on resource 'grafana_datasource[graphite]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `each' for nil:NilClass
</pre>

It seems to be caused by this:

<pre>
2015/11/20 10:24:32 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=mkdir /var/lib/grafana/sessions: permission denied)
2015/11/20 10:24:32 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=mkdir /var/lib/grafana/sessions: permission denied)
2015/11/20 10:24:32 [I] Completed /api/datasources/ 401 Unauthorized in 88.765µs
$ ls -l -d /var/lib/grafana
drwxr-xr-x. 3 root root 4096 Nov 20 09:57 /var/lib/grafana
</pre>

Restarting grafana fixes the rights of the directory (because the init script does a chown), but it looks like chef is re-changing the owner (and I can't understand why).

**Comment by JonathanTron** [comment] 2015-11-26 09:18
The error when datasources api call returns an error is fixed in https://github.com/JonathanTron/chef-grafana/commit/57c2ccfb0c2bbf680f4244c5d9a5c4da23424434.

This should fix both exceptions. About the wait on start issue, it should be handled by the retry strategy. But it will always have a timeout limit, so if it's really slow, only a second run will help there.

**Comment by gretel** [comment] 2015-11-26 12:13
@JonathanTron great thanks going to test and feed back. is there a easy way to configure timeout interval?

**Comment by gretel** [comment] 2015-12-04 11:18
@JonathanTron works fine now. adjustable timeout'd be great

**Comment by cyberflow** [comment] 2016-02-02 11:23
Same issue with organization list:

```
       [2016-02-02T10:59:12+00:00] ERROR: Connection refused.
       [2016-02-02T10:59:12+00:00] ERROR: Connection refused.


           ================================================================================
           Error executing action `create` on resource 'grafana_datasource[statsd]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `length' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:119:in `_check_org!'
           /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:126:in `_select_org'
           /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:25:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/wz-grafana/recipes/default.rb

            22: grafana_datasource 'statsd' do
            23:   admin_password node['grafana']['ini']['security']['admin_password']
            24:   datasource(
            25:     type: 'influxdb',
            26:     url: 'http://127.0.0.1:8086',
            27:     access: 'proxy',
            28:     database: 'statsd',
            29:     user: 'statsd',
            30:     password: 'statsd',
            31:     isdefault: false
            32:   )
            33:   action :create
            34: end
            35:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/wz-grafana/recipes/default.rb:22:in `from_file'

           grafana_datasource("statsd") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :grafana_datasource
             cookbook_name "wz-grafana"
             recipe_name "default"
             admin_password "admin"
             datasource {:type=>"influxdb", :url=>"http://127.0.0.1:8086", :access=>"proxy", :database=>"statsd", :user=>"statsd", :password=>"statsd", :isdefault=>false, :name=>"statsd"}
             host "localhost"
             port 3000
             admin_user "admin"
           end
```

**Comment by JonathanTron** [comment] 2016-03-27 09:57
PR making sure `get_org_list` always returns an Array was merged in master and should fix this issue.

**Closed as completed by JonathanTron** 2016-03-27 09:57 UTC
