### ISSUE TITLE
Unable to create a datasource

### ISSUE THREAD

**Issue by nilroy** [sous-chefs/grafana#238] opened 2019-04-23 12:35 UTC
### Cookbook version
v4.0.2

### Chef-client version
13.8.5-1

### Platform Details
Debian 4.19.28-2~bpo9+1 runing in AWS

### Scenario:
Trying to create datasource using the following 

```
grafana_datasource 'InfluxDB' do
  datasource(
    type: 'influxdb',
    url: '<influxdb url>',
    access: 'proxy',
    database: '<db name>'
  )
  action :create
  admin_user '<admin username>'
  admin_password '<admin password>'
end
```

Used the admin username and password for grafana

### Expected Result:
The datasource should be created

### Actual Result:
Datasource is not created and getting below logs from the chef-client run

```[2019-04-23T12:01:35+00:00] INFO: Processing grafana_datasource[InfluxDB] action create (nosto-grafana::datasources line 34)
[2019-04-23T12:01:35+00:00] ERROR: Invalid grafana_user and grafana_sess.
[2019-04-23T12:01:35+00:00] ERROR: Invalid grafana_user and grafana_sess.
[2019-04-23T12:01:35+00:00] ERROR: Invalid grafana_user and grafana_sess.
```

**Comment by nilroy** [comment] 2019-04-24 12:47
@JonathanTron any idea about this?

**Comment by JonathanTron** [comment] 2019-04-24 12:51
Hi @nilroy, sorry I'm not involved anymore in this project.

**Comment by nilroy** [comment] 2019-04-25 06:59
@JonathanTron thanks for the information. I would not use this feature. I shall tryhttps://grafana.com/docs/administration/provisioning/#datasources for the data sources. It seems to be more stable.

**Comment by nilroy** [comment] 2019-04-25 07:28
But there is some issue authenticating through the grafana API in this cookbook. I am not able to create an organization also

**Comment by atward** [comment] 2019-05-15 00:14
@nilroy can you provide your grafana_config_auth block?

**Comment by whizz0** [comment] 2019-09-03 13:22
@nilroy try adding these resources before  your datasource definition:

```
grafana_config 'grafana'

grafana_config_auth 'grafana' do
  login_cookie_name 'grafana_sess'
end 
```

**Comment by mbaitelman** [comment] 2019-09-27 05:08
@nilroy do you have anything else from your recipe related to logins? 
We recently addressed a similar issue that was caused by using LDAP and missing a setting.

**Comment by xorima** [comment] 2019-11-03 10:44
Closing as the `login_cookie_name` has been resolved

**Closed as completed by xorima** 2019-11-03 10:44 UTC
Labels: Help Wanted, Bug, Priority: Medium
