### ISSUE TITLE
undefined method `service' for Chef::Resource::Template

### ISSUE THREAD

**Issue by atward** [sous-chefs/grafana#282] opened 2019-08-22 02:34 UTC
# :ghost: Brief Description

```
         * grafana_config[grafana] action install
           
           ================================================================================
           Error executing action `install` on resource 'grafana_config[grafana]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `service' for Chef::Resource::Template
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/grafana/resources/config.rb:85:in `block (3 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/grafana/resources/config.rb:72:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/grafana/resources/config.rb:71:in `block in class_from_file'
```

Introduced #274
https://github.com/sous-chefs/grafana/blob/968005adf5b12540af2b28ae58e9da6b6621346c/resources/config.rb#L85

## :pancakes: Cookbook version

5.5.0 .. master

## :heavy_plus_sign: Additional context

I believe the intent is to have a `service` resource, which should be outside the block.
Does raise a question though as this service would be root scoped and not the same as the one defined earlier in the custom resource.

**Comment by Xorima** [comment] 2019-08-30 07:44
PR opened to resolve this, hope to release today at some point, Sorry for the delay

**Comment by xorima** [comment] 2019-08-31 21:43
Hey @atward 

Could you give me an exact way to replicate this issue as I have tested on chef 13, 14 and 15 yet cannot reproduce your issue?

Thanks

**Comment by atward** [comment] 2019-09-03 00:41
@Xorima I also had issues reproducing. It should be obvious that it doesn't work as Template does not have service method. Seems like it's being saved cause it's enclosed in a provider. [chef code path](https://github.com/chef/chef/blob/35a63ddc192e50c45f6e94a3b270ed0e75c93668/lib/chef/resource.rb#L1329-L1335)

Performing any action on the resource outside the provider unmasks the issue
 
```
$ git show-ref HEAD
968005adf5b12540af2b28ae58e9da6b6621346c refs/remotes/origin/HEAD

$ git d
diff --git a/test/fixtures/cookbooks/test/recipes/install.rb b/test/fixtures/cookbooks/test/recipes/install.rb
index af6006d..5ca41a5 100644
--- a/test/fixtures/cookbooks/test/recipes/install.rb
+++ b/test/fixtures/cookbooks/test/recipes/install.rb
@@ -34,3 +34,5 @@ execute 'sleep 30' do
   action :nothing
   subscribes :run, 'service[grafana-server]', :immediately
 end
+
+edit_resource(:template, '/etc/grafana/grafana.ini')

$ KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen converge
[2019-09-03T00:35:45+00:00] FATAL: NoMethodError: grafana_config[Grafana] (test::install line 3) had an error: NoMethodError: undefined method `service' for Chef::Resource::Template
```

**Comment by xorima** [comment] 2019-09-03 07:28
thanks @atward 

Based on that I will look to do something similar to this: https://github.com/sous-chefs/haproxy/blob/master/documentation/haproxy_service.md

Can you see any potential issues with this configuration?

**Comment by fortman** [comment] 2019-09-25 21:38
Since the service[grafana-server] resource is defined in the grafana resources, it isn't visible from the recipes.  I get around this error by adding one line to the end of my recipe

service 'grafana-server'

This works ok with notifies, but I'm not sure what the behavior would be with subscribes, because it might be a different object inside chef.

**Comment by xorima** [comment] 2019-10-09 20:51
This should now be resolved in the latest major

**Closed as completed by xorima** 2019-10-09 20:51 UTC
Labels: Bug, Priority: High
