### ISSUE TITLE
grafana_dashboard file not found

### ISSUE THREAD

**Issue by runningman84** [sous-chefs/grafana#63] opened 2015-07-16 08:41 UTC
my recipe looks like this:

```
grafana_dashboard 'MYDASH' do
  source 'grafana'
  port 3015
  overwrite true
end
```

Funny enough the json file isn't found:

```
           ================================================================================
           Error executing action `create_if_missing` on resource 'grafana_dashboard[MYDASH]'
           ================================================================================

           RuntimeError
           ------------
           grafana/dashboard was specified, but /tmp/kitchen/cache/cookbooks/mydash/files/default/grafana/dashboard.json does not exist!

       Cookbook Trace:
           ---------------
       /tmp/kitchen/cookbooks/grafana/libraries/dashboard_api.rb:95:in `dashboard_sanity'
           /tmp/kitchen/cookbooks/grafana/providers/dashboard.rb:47:in `block in class_from_file'



~/mydash$ ls -la files/default/grafana/dashboard.json
-rw-rw-r-- 1 user group 15067 Jul 16 10:27 files/default/grafana/dashboard.json
```

The file ist stored ony my test kitchen machine at a different path:
/tmp/kitchen/cookbooks/mydash/files/default/grafana/dashboard.json instead of /tmp/kitchen/cache/cookbooks/mydash/files/default/grafana/dashboard.json

**Comment by lanyonm** [comment] 2015-07-16 12:24
I don't quite understand how the errors you posted were generated given the sample recipe code. The "________ _was specified..._" should be the `source` value of "grafana", not "grafana/dashboard". See the dashboard library for more detail: https://github.com/JonathanTron/chef-grafana/blob/master/libraries/dashboard_api.rb#L92.

Nonetheless, it looks like it's tripping over your dashboards being in `files/default/grafana` instead of `files/default`. There are several ways to work around this limitation. One is using the `path` attribute, where you could use a line like this:

``` ruby
path "#{Chef::Config[:file_cache_path]}/cookbooks/mydash/files/default/grafana/dashboard.json"
```

I'd also be interested in seeing more ways to create dashboards. We have one enhancement idea already as an open issue: https://github.com/JonathanTron/chef-grafana/issues/41.

**Comment by runningman84** [comment] 2015-07-20 10:11
I think the problem here is that the dashboard library is looking in the wrong path.

During my chef-solo run all cookbooks are stored at
/tmp/kitchen/cookbooks
But the library is looking for
/tmp/kitchen/cache/cookbooks
which does not exists.

Using chef-zero seems to solve this issue.

**Comment by JonathanTron** [comment] 2015-07-20 11:12
What version of chef are you using? 

If I remember well, `Chef::Config[:file_cache_path]` is used when synchronizing cookbooks and file, which means it would put the cookbooks in it only if `--recipe-url` is specified.

To handle it properly, we should change the providers reading files to look at `Chef::Config[:cookbook_path]` (which could be an array of path) instead of `Chef::Config[:file_cache_path]` when running in solo mode.

**Comment by runningman84** [comment] 2015-07-20 11:56
This is the latest chef version 12.4.1

**Comment by lanyonm** [comment] 2015-07-21 04:12
This is indeed a bug when using the chef_solo provisioner with test kitchen.

@JonathanTron,
The `Chef::Config[:cookbook_path]` is an array as you expected. There's likely a good, clean way to implement the iteration though the paths, but I haven't found it yet. :smile:

**Comment by JonathanTron** [comment] 2015-07-21 07:05
@lanyonm I've added a first try to take into account `Chef::Config[:cookbook_path]` when running chef-solo. I still need to verify it works as expected... will try to do that before the end of the week.

**Comment by lanyonm** [comment] 2015-07-21 15:20
I tested with `bundle exec kitchen test default-ubuntu-1404` and fixed a couple errors that popped up, but...
- The foodcritic violation being caused by https://github.com/JonathanTron/chef-grafana/blob/63-chef-solo-compat/libraries/dashboard_api.rb#L121 still needs to be resolved (but it was causing a `no implicit conversion of Symbol into String` before)
- It appears that the `Chef::Config[:cookbook_path]` is doubled up in the logging for chef_solo, but the dashboard is found on the filesystem and created successfully so maybe it's okay?

**Comment by JonathanTron** [comment] 2015-07-21 15:27
Indeed, sorry @lanyonm I forgot to push my last changes before sending the reply here. If we're using the `Chef::Config[:cookbook_path]` even for `chef zero`, then no need add it twice.

**Comment by lanyonm** [comment] 2015-07-21 15:29
I didn't even thing to check what `unshift` did. :smile: I'll pull it out.

**Comment by JonathanTron** [comment] 2015-07-21 15:32
@lanyon I've pushed fixes for what you found, and removed unshift (which put the given value at the start of the array, thus checking `Chef::Config[:cookbook_path]` first in case of `chef-solo`).

**Comment by lanyonm** [comment] 2015-07-21 16:39
:+1:

**Comment by lanyonm** [comment] 2015-08-07 14:36
resovled by #70

**Closed as completed by lanyonm** 2015-08-07 14:36 UTC
